import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeToggle } from './components';
import { Suspense } from 'react';
import Loading from './loading';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<Loading />}>
          <div className="bg-slate-200 dark:bg-gray-800 text-slate-800 dark:text-slate-200 min-h-screen">
            <div className="flex justify-end p-4">
              <ThemeToggle />
            </div>
            <div className="p-4 flex justify-center items-center flex-col h-full gap-3">
              {children}
            </div>
          </div>
        </Suspense>
      </body>
    </html>
  );
}
